name: CICD

# spell-checker:ignore CICD CODECOV MSVC MacOS Peltoche SHAs buildable clippy dpkg esac fakeroot gnueabihf halium libssl mkdir musl popd printf pushd rustfmt softprops toolchain

env:
  PROJECT_NAME: clp
  PROJECT_DESC: "An Command show local installed packages"
  RUST_MIN_SRV: "1.43.1"

on: [push, pull_request]

jobs:
  style:
    name: Style
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job: [ { os: ubuntu-latest }, { os: macos-latest }, { os: windows-latest } ]
    steps:
    - uses: actions/checkout@main
    - name: Install `rust` toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{env.RUST_MIN_SRV}}
        override: true
        profile: minimal
        components: rustfmt, clippy
    - name: "`fmt` testing"
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: "`clippy` testing"
      if: success() || failure()
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warning
